name: Sync READMEs to Docs

# Runs twice weekly (Sunday and Wednesday at midnight UTC) or on manual trigger
on:
  schedule:
    - cron: '0 0 * * 0'  # Sunday midnight UTC
    - cron: '0 0 * * 3'  # Wednesday midnight UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no PR created)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.README_SYNC_PAT }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml requests

      - name: Sync READMEs
        env:
          GITHUB_TOKEN: ${{ secrets.README_SYNC_PAT }}
        run: |
          python scripts/sync-readmes.py

      - name: Check for changes
        id: changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git diff --staged --stat
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true' && github.event.inputs.dry_run != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.README_SYNC_PAT }}
          commit-message: |
            docs: sync READMEs from source repositories

            Auto-synced from:
            - thenvoi/thenvoi-mcp
            - thenvoi/thenvoi-sdk-python
            - thenvoi/phoenix-channels-python-client-alpha
            - thenvoi/n8n-nodes-thenvoi
          title: "[Auto] Sync READMEs from source repositories"
          body: |
            ## Automated README Sync

            This PR was automatically generated by the README sync workflow.

            ### Repositories synced:
            - [thenvoi-mcp](https://github.com/thenvoi/thenvoi-mcp)
            - [thenvoi-sdk-python](https://github.com/thenvoi/thenvoi-sdk-python)
            - [phoenix-channels-python-client-alpha](https://github.com/thenvoi/phoenix-channels-python-client-alpha)
            - [n8n-nodes-thenvoi](https://github.com/thenvoi/n8n-nodes-thenvoi) (private)

            ### Review checklist:
            - [ ] Check that extracted sections look correct
            - [ ] Verify images and links are working
            - [ ] Confirm navigation structure (if new pages added)

            ---
            *This PR was auto-generated by the [sync-readmes workflow](.github/workflows/sync-readmes.yml)*
          branch: auto/sync-readmes
          base: main
          labels: |
            documentation
            automated
          delete-branch: true

      - name: Dry run summary
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "## Dry Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.changes.outputs.has_changes }}" == "true" ]; then
            echo "Changes would be made:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            git diff --staged --stat >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "No changes would be made." >> $GITHUB_STEP_SUMMARY
          fi
